spring:
  thymeleaf:
    cache: true
  threads:
    virtual:
      enabled: true
  server:
    port: 8080
    compression:
      enabled: true
    http2:
      enabled: true
    ssl:
      key-store: classpath:keystore.jks
      key-store-password: 8tung4SSL!
      key-alias: ksbrwsk_de
      enabled: true
